### ISSUE TITLE
How to use SwissBert for embeddings

### ISSUE THREAD

**Issue by rnckp** [ZurichNLP/swissbert#1]
How can I use SwissBert for embedding documents? 

I can run your example for masked language modeling that you provide on HF just fine. However, I struggle to use your model for embeddings. 

Could you be so kind and possibly point to some example code?

Thanks very much in advance. And thanks very much too for making SwissBert available! 👍

**Comment by jvamvas** [comment]
Hi @rnckp, it is not usually recommended to embed documents directly with masked language models, because they have not been trained on this task.

However, you could fine-tune SwissBERT on the task of embedding documents. You could use a self-supervised objective such as https://github.com/princeton-nlp/SimCSE.

**Comment by rnckp** [comment]
Hey @jvamvas Thanks a lot for your quick response. That is very helpful. I will look into that. 👍
